# Hugo Gallery theme: https://github.com/nicokaiser/hugo-theme-gallery
## Adapted from: https://github.com/nicokaiser/hugo-gallery-example/tree/main

title = "Lightbridge Gallery"
languageCode = ""
copyright = "© Lightbridge"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
theme = "gallery"
timeout = "300s"

[params]
  title = "Lightbridge Gallery"
  description = "Gallery website for Lightbridge-KS"
  defaultTheme = "dark"

[author]
  name = "Kittipos Sirivongrungson"

[outputs]
  page = ["HTML"]
  home = ["HTML"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"

[menu]
[[menu.footer]]
  name = "GitHub"
  url = "https://github.com/Lightbridge-KS/gallery-lightbridge/"
  weight = 3